version: 0.0
os: linux

files:
   - source: /springbootApp.jar
     destination: /root
#   - source: /index.html
#     destination: /var/www/html
#
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
